CREATE TABLE IF NOT EXISTS USUARIO (
ID int auto_increment primary key,
NOME varchar(16),
EMAIL varchar(48),
SENHA varchar(10),
NIVEL_ACESSO varchar (10));

--INSERT INTO USUARIO (NOME, EMAIL, SENHA, NIVEL_ACESSO) VALUES ('MARCOS', 'MARCOS@EMAIL.COM', '1234', 'ADMIN');
--INSERT INTO USUARIO (NOME, EMAIL, SENHA, NIVEL_ACESSO) VALUES ('ANA', 'ANA@EMAIL.COM', '1234', 'USER');
--INSERT INTO USUARIO (NOME, EMAIL, SENHA, NIVEL_ACESSO) VALUES ('MARCIA', 'MARCIA@EMAIL.COM', '1234', 'USER');
--INSERT INTO USUARIO (NOME, EMAIL, SENHA, NIVEL_ACESSO) VALUES ('VITORIA', 'VITORIA@EMAIL.COM', '1234', 'USER');

CREATE TABLE IF NOT EXISTS PACIENTE (
id int auto_increment primary key,
nome varchar(30),
sobrenome varchar (30),
idade int (3));

INSERT INTO PACIENTE (nome, sobrenome, idade) VALUES ('Maria', 'Silva', '37');
